services:
  - type: web
    name: vtt-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 4

  - type: redis
    name: vtt-analysis-redis
    ipAllowList: []
    plan: free

  - type: worker
    name: vtt-analysis-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.tasks worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false 